window.SOLUTIONS_CASES_EN = [
  {
    id: 1,
    title: "Automated bank statement processing",
    type: "FINANCE AUTOMATION",
    short: "Raw bank statement rows → counterparty → payment purpose → category → structured result.",
    featured: false,
    priority: 62,
    concepts: [
      "automation",
      "bank",
      "payments",
      "categorization",
      "counterparty",
      "finance",
      "data_cleaning",
      "data_matching"
    ],
    tools: [
      "Excel",
      "Google Apps Script",
      "OCR"
    ],
    tags: [
      "bank",
      "payments",
      "bank statement",
      "categorization",
      "counterparty"
    ],
    aliases: [
      "bank statement processing",
      "bank statement parser",
      "bank transaction parser",
      "categorize bank transactions",
      "categorize payments",
      "identify counterparties",
      "payment categorization",
      "financial transaction automation"
    ],
    problems: [
      "I manually process bank transactions",
      "I manually categorize bank statement rows",
      "I need to identify counterparties in payments",
      "I need to categorize bank payments automatically"
    ],
    outcomes: [
      "structured payments",
      "automatic categorization",
      "identified counterparties"
    ]
  },

  {
    id: 2,
    title: "Automated parsing of PDF invoices and packing lists",
    type: "DOCUMENT AUTOMATION",
    short: "PDF in Google Drive → OCR → document type detection → line-item parsing → RAW / PACKING → archive.",
    featured: false,
    priority: 72,
    concepts: [
      "automation",
      "pdf",
      "invoice",
      "packing",
      "ocr",
      "google_drive",
      "data_matching",
      "documents"
    ],
    tools: [
      "PDF",
      "OCR",
      "Google Drive",
      "Google Docs",
      "Google Sheets",
      "Google Apps Script"
    ],
    tags: [
      "invoices",
      "packing list",
      "OCR",
      "parser",
      "PDF"
    ],
    aliases: [
      "invoice parser",
      "pdf invoice parser",
      "extract data from pdf",
      "parse pdf",
      "packing list parser",
      "read invoice pdf",
      "process pdf documents",
      "extract invoice line items"
    ],
    problems: [
      "I manually copy line items from PDF files",
      "invoice data needs to be transferred to Excel",
      "I need to recognize invoices automatically",
      "I need to read packing lists"
    ],
    outcomes: [
      "PDF line items in a table",
      "automatic OCR",
      "processed PDF archive"
    ]
  },

  {
    id: 3,
    title: "Automated dashboard creation from an Excel table",
    type: "EXCEL ANALYTICS",
    short: "200 sales rows → aggregation → KPI → charts → ready-to-use analytical dashboard.",
    featured: false,
    priority: 58,
    concepts: [
      "automation",
      "excel",
      "dashboard",
      "analytics",
      "kpi",
      "reporting",
      "sales"
    ],
    tools: [
      "Excel",
      "JavaScript",
      "Dashboard"
    ],
    tags: [
      "dashboard",
      "Excel",
      "KPI",
      "sales",
      "charts"
    ],
    aliases: [
      "excel dashboard",
      "dashboard from excel",
      "report from excel",
      "charts from excel",
      "sales dashboard",
      "excel visualization",
      "build kpi",
      "automatic excel dashboard"
    ],
    problems: [
      "I have an Excel table and need a dashboard",
      "I have sales data and need a report",
      "I need charts to be generated automatically",
      "I need KPIs from a table"
    ],
    outcomes: [
      "KPI",
      "charts",
      "analytical dashboard",
      "aggregated data"
    ]
  },

  {
    id: 4,
    title: "Production capacity and order delivery planning",
    type: "PRODUCTION PLANNING",
    short: "Orders + production lines + daily capacity → daily allocation → completion date → status and utilization.",
    featured: true,
    priority: 94,
    concepts: [
      "automation",
      "production",
      "capacity",
      "scheduling",
      "deadline",
      "priority",
      "forecast"
    ],
    tools: [
      "Production Planning",
      "Capacity",
      "Scheduling"
    ],
    tags: [
      "production",
      "capacity",
      "deadlines",
      "completion date",
      "priority"
    ],
    aliases: [
      "capacity planning",
      "production capacity",
      "production planning",
      "delivery planning",
      "when will the order be ready",
      "calculate completion date",
      "production line utilization",
      "production scheduling"
    ],
    problems: [
      "I do not know when the order will be ready",
      "I need to distribute orders between production lines",
      "I need to plan production capacity",
      "I need to account for urgent orders",
      "I need to calculate realistic completion dates"
    ],
    outcomes: [
      "completion date",
      "line utilization",
      "production calendar",
      "order status"
    ]
  },

  {
    id: 5,
    title: "Automated component requirements calculation",
    type: "BOM / PROCUREMENT",
    short: "Finished-product orders → BOM → total requirements → inventory → exact quantity of components to purchase.",
    featured: true,
    priority: 92,
    concepts: [
      "automation",
      "bom",
      "procurement",
      "stock",
      "mrp",
      "production",
      "data_matching"
    ],
    tools: [
      "BOM",
      "MRP Logic",
      "Stock",
      "Procurement"
    ],
    tags: [
      "BOM",
      "components",
      "procurement",
      "inventory",
      "requirements"
    ],
    aliases: [
      "component requirements calculation",
      "procurement planning",
      "bom calculator",
      "material requirements",
      "mrp",
      "what needs to be purchased",
      "component planning",
      "inventory requirements"
    ],
    problems: [
      "I manually calculate components for orders",
      "I manually calculate material requirements",
      "I do not know how much to purchase",
      "I need to account for available inventory",
      "I need to calculate procurement requirements"
    ],
    outcomes: [
      "exact requirements",
      "purchase list",
      "inventory accounted for",
      "component plan"
    ]
  },

  {
    id: 6,
    title: "Management reporting automation in Power BI",
    type: "MANAGEMENT BI",
    short: "ERP / 1C / SAP → Power Query → data model → DAX → interactive Power BI reporting with automated refresh.",
    featured: true,
    priority: 100,
    concepts: [
      "automation",
      "reporting",
      "powerbi",
      "dashboard",
      "analytics",
      "kpi",
      "planfact",
      "powerquery",
      "erp",
      "integration",
      "realtime",
      "sales",
      "finance"
    ],
    tools: [
      "Power BI",
      "Power Query",
      "DAX",
      "ERP",
      "SAP",
      "1C",
      "Data Gateway"
    ],
    tags: [
      "Power BI",
      "reporting",
      "dashboard",
      "DAX",
      "ERP",
      "plan vs actual"
    ],
    aliases: [
      "management reporting power bi",
      "management reporting",
      "executive dashboard",
      "bi reporting",
      "power bi report",
      "management dashboard",
      "report for management",
      "power bi automated refresh",
      "power bi from sap",
      "power bi from 1c",
      "plan vs actual dashboard"
    ],
    problems: [
      "I manually prepare a report every month",
      "there are too many versions of the Excel report",
      "management needs up-to-date figures",
      "I need plan vs actual reporting",
      "I want one reliable reporting model"
    ],
    outcomes: [
      "current version of the data",
      "automated refresh",
      "interactive analytics",
      "single data model",
      "plan vs actual"
    ]
  },

  {
    id: 7,
    title: "Automated consolidation of data from hundreds of Excel files",
    type: "DATA CONSOLIDATION",
    short: "Shared folder with Excel reports → Power Query / Power BI → cleaning → standardized structure → one dataset for analysis.",
    featured: false,
    priority: 84,
    concepts: [
      "automation",
      "excel",
      "powerquery",
      "powerbi",
      "data_consolidation",
      "data_cleaning",
      "google_drive",
      "reporting",
      "realtime"
    ],
    tools: [
      "Excel",
      "Power Query",
      "Power BI",
      "Folder"
    ],
    tags: [
      "hundreds of files",
      "consolidation",
      "Power Query",
      "folder",
      "Excel"
    ],
    aliases: [
      "combine excel files",
      "merge excel files",
      "consolidate excel reports",
      "folder consolidation",
      "power query from folder",
      "combine files from folder",
      "merge excel reports",
      "automatically import new excel files"
    ],
    problems: [
      "I manually copy data from many Excel files",
      "I manually combine multiple Excel reports",
      "new Excel reports arrive every week",
      "I need new files to be picked up automatically",
      "I need one dataset from hundreds of files"
    ],
    outcomes: [
      "single refresh",
      "single dataset",
      "automatic ingestion of new files",
      "clean data"
    ]
  },

  {
  id: 8,
  title: "Automating reminders and task follow-up with a Telegram bot",
  type: "TELEGRAM AUTOMATION",
  short: "Message or task → choose a time → reminder → snooze / complete / pass to someone else.",
  featured: false,
  priority: 78,
  concepts: [
    "automation",
    "telegram",
    "bot",
    "notifications",
    "realtime"
  ],
  tools: [
    "Telegram",
    "Telegram Bot API",
    "Google Apps Script"
  ],
  tags: [
    "Telegram",
    "bot",
    "reminders",
    "tasks",
    "follow-up"
  ],
  aliases: [
    "telegram bot",
    "reminder bot",
    "telegram reminders",
    "task reminder bot",
    "follow-up bot",
    "telegram task automation",
    "remind me later",
    "message to reminder",
    "repeat reminder"
  ],
  problems: [
    "tasks get lost in chats",
    "messages get buried in Telegram",
    "I forget to follow up",
    "I need reminders for client tasks",
    "I want to create reminders from messages",
    "I forget to reply to clients",
    "I need repeated reminders until a task is completed"
  ],
  outcomes: [
    "automatic reminders",
    "task control",
    "repeat reminders",
    "fewer missed tasks",
    "better follow-up control",
    "tasks directly in Telegram"
  ]
  },

  {
    id: 9,
    title: "From customer inquiry to ready-to-send sales quotation",
    type: "SALES AUTOMATION",
    short: "Incoming email → Sales Quotations app → customer → products and prices → delivery → PDF → save → send.",
    featured: false,
    priority: 82,
    concepts: [
      "automation",
      "sales",
      "quotation",
      "documents",
      "workflow",
      "integration",
      "crm",
      "erp"
    ],
    tools: [
      "Outlook",
      "Excel",
      "ERP",
      "CRM",
      "1C",
      "PDF"
    ],
    tags: [
      "quotation",
      "sales quotation",
      "commercial offer",
      "sales automation",
      "CRM",
      "ERP",
      "Excel",
      "PDF"
    ],
    aliases: [
      "sales quotation automation",
      "quotation automation",
      "commercial offer automation",
      "automated quotation process",
      "create quotation from email",
      "generate quotation from customer request",
      "sales quote generator",
      "quotation workflow",
      "automated commercial offer",
      "generate pdf quotation",
      "prices from excel",
      "prices from erp",
      "prices from 1c",
      "customer data from crm"
    ],
    problems: [
      "I prepare quotations manually",
      "I manually copy customer requests from email",
      "I search for customer data in CRM or ERP",
      "I search for product prices in Excel or ERP",
      "I copy prices between different systems",
      "I sometimes use outdated price lists",
      "old customer data remains in copied quotation templates",
      "delivery costs are calculated separately",
      "I manually create PDF quotations",
      "quotation history is scattered across files and systems"
    ],
    outcomes: [
      "guided quotation workflow",
      "customer request imported from email",
      "customer data loaded from the selected source",
      "products and prices loaded from the selected source",
      "delivery included in the quotation process",
      "automatic PDF generation",
      "quotation saved in one module",
      "prepared customer email with PDF attachment",
      "less manual copying",
      "fewer quotation errors"
    ]
  },
{
  id: 10,
  title: "Automated contract generation from an approved template",
  type: "CONTRACT AUTOMATION",
  short: "Client details + legal and banking information + commercial terms → approved contract template → validation → print or PDF.",
  featured: true,
  priority: 88,
  concepts: [
    "automation",
    "contract",
    "documents",
    "document_generation",
    "template",
    "excel",
    "vba",
    "pdf",
    "data_entry",
    "workflow"
  ],
  tools: [
    "Excel",
    "VBA",
    "Word",
    "PDF"
  ],
  tags: [
    "contract",
    "contract generator",
    "document automation",
    "contract template",
    "client details",
    "Excel",
    "VBA",
    "PDF"
  ],
  aliases: [
    "automated contract generation",
    "automatic contract generator",
    "contract generator",
    "generate contract automatically",
    "contract automation",
    "agreement generator",
    "service agreement generator",
    "generate agreement from template",
    "contract from template",
    "agreement from template",
    "populate contract automatically",
    "auto-fill contract",
    "insert client details into contract",
    "populate contract with client data",
    "contract from excel",
    "generate contract from excel",
    "excel contract generator",
    "generate agreement from client data",
    "document generation",
    "document automation",
    "automated document creation",
    "generate contract pdf",
    "export agreement to pdf",
    "contract workflow automation"
  ],
  problems: [
    "every new contract starts as a copy of the previous one",
    "I manually replace client details in contracts",
    "I have to find every reference to the previous client",
    "old client information can remain in a copied contract",
    "I enter the same information several times",
    "I manually update company names and authorized representatives",
    "I manually update addresses bank details and iban",
    "standard contracts take too long to prepare",
    "different employees format contracts differently",
    "I need to generate contracts automatically from a template",
    "I need to create contracts from client data",
    "I want to fill out a form and generate a contract",
    "I need contracts generated as PDF files"
  ],
  outcomes: [
    "ready-to-use contract from an approved template",
    "automatic insertion of client details",
    "consistent contract formatting",
    "less manual copying",
    "fewer errors in legal and banking details",
    "automatic insertion of commercial terms",
    "live contract preview",
    "automatic page numbering",
    "configurable document formatting",
    "print-ready contract",
    "PDF contract export"
  ]
},
{
  id: 11,
  title: "Automated accounts receivable follow-up from past due to resolution",
  type: "FINANCE / CLOSED-LOOP AUTOMATION",
  short: "SAP / 1C → past-due invoice → ready-to-send email → manager approval → payment monitoring → escalation → automatic case closure.",
  featured: true,
  priority: 112,
  desktopNoteTitle: "Best viewed on desktop",
  desktopNote: "For the best experience with this interactive model, we recommend opening this case on a desktop or laptop.",
  concepts: [
    "automation",
    "finance",
    "payments",
    "erp",
    "integration",
    "telegram",
    "notifications",
    "email",
    "documents",
    "crm",
    "realtime"
  ],
  tools: [
    "SAP",
    "1C",
    "ERP",
    "Telegram",
    "Email",
    "Automation"
  ],
  tags: [
    "accounts receivable",
    "AR automation",
    "collections",
    "past-due invoices",
    "payment follow-up",
    "SAP",
    "1C"
  ],
  aliases: [
    "accounts receivable",
    "accounts receivable automation",
    "automated accounts receivable",
    "accounts receivable workflow",
    "accounts receivable follow up",
    "accounts receivable follow-up",
    "ar automation",
    "ar workflow",
    "ar follow up",
    "ar follow-up",
    "ar collections",
    "automated collections",
    "collections automation",
    "collections workflow",
    "collection process",
    "customer collections",
    "receivables automation",
    "receivables management",
    "receivables follow up",
    "receivables follow-up",
    "past due invoice",
    "past-due invoice",
    "past due invoices",
    "past-due invoices",
    "overdue invoice",
    "overdue invoices",
    "unpaid invoice",
    "unpaid invoices",
    "late invoice",
    "late payment",
    "late customer payment",
    "customer pays late",
    "customer not paying",
    "customer has not paid",
    "customer hasn't paid",
    "customer owes money",
    "outstanding invoice",
    "outstanding invoices",
    "outstanding balance",
    "open receivables",
    "open customer balance",
    "payment reminder",
    "payment reminders",
    "automated payment reminder",
    "automatic payment reminders",
    "invoice reminder",
    "invoice reminders",
    "overdue payment reminder",
    "payment follow up",
    "payment follow-up",
    "follow up on unpaid invoices",
    "follow up overdue invoices",
    "chase overdue invoices",
    "chase unpaid invoices",
    "customer payment follow up",
    "customer payment follow-up",
    "payment collection",
    "debt collection",
    "commercial collections",
    "collection escalation",
    "collections escalation",
    "past due escalation",
    "overdue invoice escalation",
    "promise to pay",
    "promise-to-pay",
    "promise to pay tracking",
    "track customer payment promise",
    "promised payment date",
    "customer promised to pay",
    "broken promise to pay",
    "missed promise to pay",
    "partial payment",
    "partial invoice payment",
    "partial payment tracking",
    "remaining balance",
    "payment confirmation",
    "payment proof",
    "payment verification",
    "formal demand",
    "formal demand letter",
    "demand for payment",
    "collection letter",
    "collections letter",
    "past due notice",
    "final payment reminder",
    "legal collection handoff",
    "legal review package",
    "accounts receivable audit trail",
    "collections audit trail",
    "closed loop collections",
    "closed-loop collections",
    "closed loop accounts receivable",
    "closed-loop accounts receivable",
    "closed loop ar automation",
    "invoice collection automation",
    "invoice follow up automation",
    "invoice follow-up automation",
    "sap accounts receivable automation",
    "sap collections automation",
    "1c accounts receivable automation"
  ],
  problems: [
    "I manually check overdue invoices",
    "I manually check past-due invoices",
    "I have to keep checking whether customers paid",
    "I keep checking customer balances in SAP",
    "I keep checking customer balances in 1C",
    "I have to monitor unpaid invoices manually",
    "I forget to follow up on overdue invoices",
    "I forget to send second payment reminders",
    "I forget which customers need another follow-up",
    "customers pay late and I have to chase them manually",
    "customer payment promises get lost in email",
    "a customer promised to pay and nobody checked again",
    "I need to track promise-to-pay dates",
    "I need automatic reminders for overdue invoices",
    "I need automatic customer payment follow-ups",
    "every account manager writes collection emails differently",
    "there is no consistent collections process",
    "there is no complete history of collection activity",
    "partial payments require manual recalculation",
    "after a partial payment I have to calculate the remaining balance",
    "I do not know when to escalate an overdue invoice",
    "collections depend on the account manager remembering everything",
    "there is no automatic escalation for past-due invoices",
    "I need manager approval before certain collection emails are sent",
    "I need to pause reminders when a customer promises to pay",
    "I need to stop automation when a customer disputes an invoice",
    "I need a complete audit trail for accounts receivable follow-up",
    "I need to know when to send a formal demand",
    "I need to automatically close the case when payment is received"
  ],
  outcomes: [
    "automatic past-due invoice detection",
    "automatic payment status checks",
    "automated accounts receivable follow-up",
    "ready-to-send customer emails",
    "manager approval through Telegram",
    "consistent collection communication",
    "automatic payment reminders",
    "promise-to-pay tracking",
    "automatic pause until the promised payment date",
    "automatic escalation when payment is not received",
    "partial payment detection",
    "automatic outstanding balance recalculation",
    "future emails based on the actual remaining balance",
    "payment confirmation verification",
    "automation paused when a dispute is detected",
    "formal demand prepared automatically",
    "human approval before formal escalation",
    "legal review package assembled automatically",
    "complete Audit Trail",
    "full history of system and manager decisions",
    "automatic case closure after full payment",
    "closed-loop accounts receivable workflow"
  ]
},
{
  id: 12,
  title: "Transport operations management without a heavyweight TMS",
  type: "TRANSPORT OPERATIONS AUTOMATION",
  short: "Email / phone / messaging apps / freight exchanges → one shipment register → planning → truck and driver assignment → trip execution → ETA → POD / CMR → analytics.",
  featured: true,
  priority: 118,

  desktopNoteTitle: "Best viewed on desktop",
  desktopNote: "For the best experience with this interactive model, we recommend opening this case on a desktop or laptop.",

  concepts: [
    "automation",
    "integration",
    "google_sheets",
    "apps_script",
    "email",
    "documents",
    "notifications",
    "realtime",
    "analytics",
    "dashboard",
    "kpi",
    "erp",
    "crm",
    "transport",
    "logistics",
    "fleet",
    "tms",
    "tracking"
  ],

  tools: [
    "Google Sheets",
    "Google Apps Script",
    "Email",
    "Telegram",
    "HTML",
    "JavaScript"
  ],

  tags: [
    "logistics",
    "transport",
    "shipments",
    "dispatcher",
    "logistics coordinator",
    "driver",
    "fleet",
    "route",
    "ETA",
    "CMR",
    "POD",
    "Track & Trace",
    "freight exchange",
    "carrier",
    "TMS"
  ],

  aliases: [
    "transport automation",
    "transport operations",
    "transport operations automation",
    "transport management",
    "transport workflow",
    "transport management workflow",
    "shipment management",
    "shipment operations",
    "shipment workflow",
    "freight operations",
    "freight management",
    "logistics automation",
    "logistics workflow",
    "logistics operations",
    "dispatch automation",
    "transport dispatch",
    "dispatch system",
    "dispatcher system",
    "dispatcher workflow",
    "logistics coordinator workflow",

    "shipment register",
    "transport register",
    "freight register",
    "shipment requests",
    "transport requests",
    "freight requests",
    "transport orders",
    "shipment orders",
    "manage shipment requests",
    "manage transport requests",
    "all transport requests in one place",

    "fleet management",
    "fleet control",
    "company fleet",
    "own fleet",
    "own trucks",
    "third party carrier",
    "third-party carrier",
    "external carrier",
    "carrier management",
    "carrier assignment",
    "carrier selection",
    "assign carrier",
    "assign truck",
    "truck assignment",
    "vehicle assignment",
    "assign driver",
    "driver assignment",
    "driver management",
    "truck availability",
    "driver availability",
    "available truck",
    "available driver",

    "transport planning",
    "shipment planning",
    "trip planning",
    "route planning",
    "dispatch planning",
    "fleet planning",
    "resource planning",

    "shipment status",
    "trip status",
    "delivery status",
    "pickup",
    "loading",
    "in transit",
    "delivered",
    "shipment delay",
    "delivery delay",
    "late delivery",
    "late shipment",
    "delay risk",

    "eta",
    "delivery eta",
    "shipment eta",
    "eta tracking",
    "eta management",
    "eta update",
    "updated eta",
    "estimated time of arrival",
    "expected delivery time",
    "delivery forecast",
    "arrival time",

    "track and trace",
    "track & trace",
    "tracking",
    "shipment tracking",
    "delivery tracking",
    "freight tracking",
    "transport tracking",
    "track shipment",
    "track delivery",
    "customer tracking",

    "cmr",
    "pod",
    "proof of delivery",
    "shipment documents",
    "transport documents",
    "delivery documents",
    "cmr document",
    "pod document",
    "delivery confirmation",
    "proof of delivery document",

    "freight exchange",
    "freight marketplace",
    "transport exchange",
    "load board",
    "lardi",
    "lardi trans",
    "lardi-trans",
    "della",

    "tms",
    "transport management system",
    "without tms",
    "tms alternative",
    "lightweight tms",
    "simple tms",
    "tms for small business",
    "tms for carrier",
    "tms for transport company",
    "replace tms",
    "alternative to tms",

    "google sheets logistics",
    "google sheets transport",
    "google sheets shipments",
    "shipment spreadsheet",
    "transport spreadsheet",
    "dispatcher spreadsheet",
    "logistics spreadsheet",
    "transport operations in google sheets",
    "google sheets fleet management",
    "apps script logistics",

    "email shipment request",
    "shipment request from email",
    "shipment request from phone",
    "shipment request from messenger",
    "shipment request from whatsapp",
    "shipment request from telegram",
    "shipment request from website",
    "shipment request from freight exchange",

    "transport control tower",
    "logistics control tower",
    "fleet dashboard",
    "transport dashboard",
    "shipment dashboard",
    "transport kpi",
    "fleet kpi",

    "owner dashboard logistics",
    "customer shipment tracking",
    "driver mobile interface",
    "driver app",
    "driver workflow",

    "transport automation google sheets",
    "logistics automation google sheets",
    "lightweight transport management",
    "transport system without expensive tms"
  ],

  problems: [
    "shipment requests arrive through email phone messaging apps and freight exchanges",
    "transport requests are scattered across different channels",
    "dispatcher manually copies shipment requests into a spreadsheet",
    "logistics coordinator manually searches for an available truck",
    "I cannot see which trucks are available",
    "I cannot see which drivers are available",
    "a truck can accidentally be assigned while it is already in transit",
    "the wrong equipment type can be assigned to a shipment",
    "truck payload capacity can be exceeded",
    "pallet capacity can be exceeded",
    "drivers report status by phone or messaging app",
    "customers keep calling to ask where the truck is",
    "customers cannot see the current eta",
    "shipment delays have to be communicated manually",
    "a dispatcher has to notify every stakeholder separately",
    "cmr documents are stored separately from the shipment",
    "pod documents get lost in email or chat",
    "there is no single shipment history",
    "there is no single shipment register",
    "there is no consistent shipment status",
    "the owner cannot see which shipments require attention",
    "the owner cannot see fleet utilization",
    "the owner cannot see shipment margins",
    "we use both company trucks and third-party carriers",
    "we need to manage transportation without a heavyweight tms",
    "we need shipment tracking without buying a full tms",
    "transport operations depend on spreadsheets phone calls and messages",
    "we need one workflow from shipment request to proof of delivery"
  ],

  outcomes: [
    "single shipment register",
    "all transport requests in one place",
    "automatic order creation from incoming requests",
    "company fleet control",
    "third-party carrier control",
    "truck availability validation",
    "payload capacity validation",
    "equipment type validation",
    "driver availability control",
    "truck and driver assignment",
    "structured shipment workflow",
    "shipment statuses in one process",
    "current eta",
    "automatic eta update after a delay",
    "automatic customer notifications",
    "customer track and trace",
    "cmr attached to the shipment",
    "pod attached to the shipment",
    "complete shipment history",
    "truck released after delivery",
    "driver released after delivery",
    "shipments requiring attention",
    "owner control tower",
    "active shipment kpis",
    "delivery kpis",
    "on-time delivery tracking",
    "fleet utilization tracking",
    "revenue cost and margin visibility",
    "analysis of shipment request channels",
    "one status update visible across all roles",
    "dispatcher logistics coordinator driver customer and owner work in one connected process"
  ]
}
];
